export enum EstadoPasajero {
  FACTURANDO_EQUIPAJE,
  ESPERANDO_FACTURACION,
  EN_CONTROL_METALES,
  ESPERANDO_CONTROL,
  COMPRANDO_BILLETE,
  ESPERANDO_COMPRA_BILLETE,
  CHEQUEANDO_BILLETE,
  ESPERANDO_CHEQUEO_BILLETE,
  PASANDO_A_FACTURACION,
  PASANDO_A_CHEQUEO_BILLETE,
  PASANDO_A_CONTROL_METALES
}