export enum EventoAlt {
  INICIO_SIMULACION,
  LLEGADA_PASAJERO,
  FIN_FACTURACION_VENTA,
  FIN_CHEQUEO_BILLETE,
  FIN_CONTROL_METALES,
  FIN_PASO_ENTRE_VENTA_FACTURACION_Y_CONTROL,
  FIN_PASO_ENTRE_CHEQUEO_Y_CONTROL,
  FIN_PASO_ENTRE_CONTROL_Y_EMBARQUE,
  FIN_SIMULACION
}